### ISSUE TITLE
Scrolling wheelScale

### ISSUE THREAD

**Issue by z3t0** [voxel/voxel-inventory-hotbar#9]
Scrolling does not seem to work here? But I think it should since its a part of the code (havent looked in deeply)

**Comment by z3t0** [comment]
```js
 console.log('mousewheel', ev);
```
That line does not get run so it seems to be a event problem

**Comment by z3t0** [comment]
Just found the wheelEnable variable. Will take a look

**Comment by z3t0** [comment]
ok turning that on gives me console output but the scrolling does not affect the hot bar

**Comment by z3t0** [comment]
https://github.com/deathcap/voxel-inventory-hotbar/blob/master/hotbar.coffee#L104
Always returns 0

**Comment by z3t0** [comment]
I think something was wrong with the logic of that part?
I get 120 (scroll up) or -120 (scroll down) What values do you get on your mouse?

**Comment by z3t0** [comment]
I fixed it

**Comment by z3t0** [comment]
will commit soon

**Comment by z3t0** [comment]
Scrolling continues to work when in the chat console, we should make it stop

**Comment by z3t0** [comment]
Almost done, I'll commit soon

**Comment by deathcap** [comment]
I also get ±120 on a Microsoft IntelliMouse (haven't had a chance to try on a Magic Mouse yet), will update the default wheelScale from 1 to 120 - unclear if there are other valid scale values, but at least this works on both of our mice.
